apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
  labels:
    app: postgresql
    component: primary
type: Opaque
stringData:
  postgres-password: "postgres123"
  custom-user-password: "psqluser123"
  replication-password: "ReplicationPass123"